"""add available amount field in balance model

Revision ID: 3dbd59d2055f
Revises: b70ab10acaef
Create Date: 2025-06-10 12:48:33.696885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dbd59d2055f'
down_revision: Union[str, None] = 'b70ab10acaef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('available', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance', 'available')
    # ### end Alembic commands ###
