"""add indexes in balance model

Revision ID: 6c3dac531340
Revises: 3dbd59d2055f
Create Date: 2025-06-11 19:51:41.806886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3dac531340'
down_revision: Union[str, None] = '3dbd59d2055f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('index_balance_user_ticker', 'balance', ['user_id', 'ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_balance_user_ticker', table_name='balance')
    # ### end Alembic commands ###
