"""Make user_id in instruments nullable and set null on delete

Revision ID: b70ab10acaef
Revises: 251ecf2b22e9
Create Date: 2025-06-07 18:42:04.689586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70ab10acaef'
down_revision: Union[str, None] = '251ecf2b22e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instruments', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('instruments_user_id_fkey', 'instruments', type_='foreignkey')
    op.create_foreign_key(None, 'instruments', 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instruments', type_='foreignkey')
    op.create_foreign_key('instruments_user_id_fkey', 'instruments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('instruments', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
