"""add indexies in orders model

Revision ID: e581803a9074
Revises: 6c3dac531340
Create Date: 2025-06-13 13:07:16.674499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e581803a9074'
down_revision: Union[str, None] = '6c3dac531340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_balance_user_ticker', table_name='balance')
    op.create_index('idx_balance_ticker_amount', 'balance', ['ticker', 'amount'], unique=False)
    op.create_index('idx_balance_user_ticker', 'balance', ['user_id', 'ticker'], unique=True)
    op.create_index('index_orders_price_timestamp', 'orders', ['price', 'timestamp'], unique=False)
    op.create_index('index_orders_ticker_direction_status', 'orders', ['ticker', 'direction', 'status'], unique=False)
    op.create_index('idx_transactions_buyer_seller', 'transactions', ['buyer_id', 'seller_id'], unique=False)
    op.create_index('idx_transactions_ticker_timestamp', 'transactions', ['ticker', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transactions_ticker_timestamp', table_name='transactions')
    op.drop_index('idx_transactions_buyer_seller', table_name='transactions')
    op.drop_index('index_orders_ticker_direction_status', table_name='orders')
    op.drop_index('index_orders_price_timestamp', table_name='orders')
    op.drop_index('idx_balance_user_ticker', table_name='balance')
    op.drop_index('idx_balance_ticker_amount', table_name='balance')
    op.create_index('index_balance_user_ticker', 'balance', ['user_id', 'ticker'], unique=False)
    # ### end Alembic commands ###
